server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 213546

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 121329340901-4fl7bbuo53nmjccrmhoo3pbc6l8qcvh2.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 193832933473449
            client-secret: 2a2febae52a199b9738b231adcd488fb
            scope:
              - email
              - public_profile
